name: wm01-ox
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - notebook=6.1.4
  - mkl-service=2.3.0
  - jupyterhub=1.1.0
  - numpy=1.19.1
  - matplotlib=3.3.1
  - pandas=1.1.3
  - scipy=1.5.0
  - pymc3=3.9.2
  - seaborn=0.11
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.2
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - python-graphviz=0.14.2
  - nose=1.3.7
  - pip=20.2.3
  - biopython=1.78
  - requests=2.24.0
  - pyyaml=5.3.1
  - scikit-learn-extra=0.1.0b2
  - ipywidgets=7.5.1
  - sympy=1.6.2
  - pytables=3.6.1
  - pip:
      - adskalman==0.3.11
      - arviz==0.10.0
      # - dabest==0.3
      # - showast==0.2.4
